#!/bin/bash

echo "🔐 GitHub Authentication Setup"
echo "=============================="
echo ""
echo "GitHub no longer accepts passwords for Git operations."
echo "You need to use a Personal Access Token (PAT)."
echo ""
echo "📝 Steps to create a Personal Access Token:"
echo ""
echo "1. Go to: https://github.com/settings/tokens"
echo "2. Click 'Generate new token' → 'Generate new token (classic)'"
echo "3. Give it a name: 'Support-Desk-Push'"
echo "4. Select expiration (30 days, 60 days, or no expiration)"
echo "5. Check the 'repo' scope (this gives full repository access)"
echo "6. Click 'Generate token' at the bottom"
echo "7. ⚠️  COPY THE TOKEN IMMEDIATELY (you won't see it again!)"
echo ""
echo "🔑 Then run this command:"
echo "   git push origin main"
echo ""
echo "When prompted:"
echo "  Username: sathish0723-tech"
echo "  Password: [paste your Personal Access Token here]"
echo ""
echo "The token will be saved in your keychain for future use."
echo ""

