#!/bin/bash

echo "🔍 Testing Git Push Authentication"
echo "==================================="
echo ""
echo "The error 'Invalid username or token' means:"
echo "  1. Your Personal Access Token expired"
echo "  2. Your token was revoked"
echo "  3. Your token doesn't have 'repo' permissions"
echo "  4. You're entering the wrong token"
echo ""
echo "📝 To fix this:"
echo ""
echo "1. Go to: https://github.com/settings/tokens"
echo "2. Check if your existing token is still there and active"
echo "3. If expired/revoked, create a NEW token:"
echo "   - Click 'Generate new token' → 'Generate new token (classic)'"
echo "   - Name: 'Support-Desk-Push'"
echo "   - Expiration: Choose your preference"
echo "   - Scope: Check 'repo' (full repository access)"
echo "   - Click 'Generate token'"
echo "   - COPY THE TOKEN IMMEDIATELY"
echo ""
echo "4. Then run: git push origin main"
echo ""
echo "5. When prompted:"
echo "   Username: sathish0723-tech"
echo "   Password: [Paste your NEW Personal Access Token]"
echo ""
echo "The token will be saved in your macOS Keychain for future use."
echo ""

